// src/app/components/LanguageSwitcher.tsx
import { useTranslation } from 'react-i18next';
import { Languages } from 'lucide-react';

const locales = [
  { code: 'en' as const, label: 'EN' },
  { code: 'tr' as const, label: 'TR' },
];

type Variant = 'dark' | 'light';

export function LanguageSwitcher({
  compact = false,
  variant = 'dark',
}: {
  compact?: boolean;
  variant?: Variant;
}) {
  const { i18n, t } = useTranslation();
  const isDark = variant === 'dark';

  return (
    <div
      className={`flex items-center gap-1 rounded-lg border p-0.5 ${compact ? '' : 'px-1'} ${
        isDark ? 'border-white/10 bg-white/5' : 'border-[#E2E8F0] bg-[#FAFBFC]'
      }`}
      role="group"
      aria-label={t('layout.language')}
    >
      {!compact && (
        <Languages
          className={`w-3.5 h-3.5 ml-1 flex-shrink-0 hidden sm:block ${isDark ? 'text-white/40' : 'text-[#94A3B8]'}`}
        />
      )}
      {locales.map(({ code, label }) => (
        <button
          key={code}
          type="button"
          onClick={() => void i18n.changeLanguage(code)}
          className={`min-w-[2rem] rounded-md px-2 py-1 text-xs font-semibold transition-colors ${
            i18n.language === code
              ? 'bg-[#D4A853] text-white'
              : isDark
                ? 'text-white/50 hover:text-white/80'
                : 'text-[#64748B] hover:text-[#0A1628]'
          }`}
        >
          {label}
        </button>
      ))}
    </div>
  );
}

// frontend/components/shared/LanguageSwitcher.vue
<script setup lang="ts">
import { Languages } from 'lucide-vue-next';

const props = withDefaults(defineProps<{ collapsed?: boolean }>(), {
  collapsed: false,
});

const { locale, locales, setLocale } = useI18n();

const options = computed(() =>
  (locales.value as Array<{ code: string; name?: string }>).map((l) => ({
    code: l.code,
    name: l.name ?? l.code.toUpperCase(),
    short: l.code.toUpperCase(),
  })),
);

async function switchLocale(code: string) {
  if (locale.value === code) return;
  await setLocale(code);
}

async function toggleLocale() {
  const next = options.value.find((opt) => opt.code !== locale.value);
  if (!next) return;
  await switchLocale(next.code);
}
</script>

<template>
  <button
    v-if="props.collapsed"
    type="button"
    class="flex w-full items-center justify-center rounded-xl p-2.5 text-white/50 transition-all hover:bg-white/5 hover:text-white"
    :title="`Language: ${locale.toUpperCase()}`"
    @click="toggleLocale"
  >
    <Languages class="h-5 w-5" />
  </button>

  <div v-else class="grid w-full grid-cols-2 gap-1">
    <button
      v-for="opt in options"
      :key="opt.code"
      type="button"
      class="flex items-center justify-center rounded-xl px-3 py-2.5 text-sm font-medium transition-all"
      :class="
        locale === opt.code
          ? 'bg-white/10 text-white'
          : 'text-white/50 hover:bg-white/5 hover:text-white'
      "
      :aria-pressed="locale === opt.code"
      :title="opt.name"
      @click="switchLocale(opt.code)"
    >
      {{ opt.short }}
    </button>
  </div>
</template>
