// frontend/components/transaction/StageBadge.vue
<script setup lang="ts">
import type { Stage } from '~/utils/demo-data';
import { STAGE_COLORS, STAGE_LABELS } from '~/utils/demo-data';

const props = withDefaults(
  defineProps<{ stage: Stage; size?: 'sm' | 'md' }>(),
  { size: 'md' },
);

const colors = computed(() => STAGE_COLORS[props.stage]);
const label = computed(() => STAGE_LABELS[props.stage]);
const cls = computed(() =>
  props.size === 'sm' ? 'text-[10px] px-2 py-0.5' : 'text-xs px-2.5 py-1',
);
</script>

<template>
  <span
    class="inline-flex items-center rounded-full font-medium"
    :class="cls"
    :style="{ backgroundColor: colors.bg, color: colors.text }"
  >
    {{ label }}
  </span>
</template>

// src/app/components/StageBadge.tsx
import { Stage, STAGE_LABELS, STAGE_COLORS } from '../data/mockData';

interface StageBadgeProps {
  stage: Stage;
  size?: 'sm' | 'md';
}

export function StageBadge({ stage, size = 'md' }: StageBadgeProps) {
  const colors = STAGE_COLORS[stage];
  const label = STAGE_LABELS[stage];
  const padding = size === 'sm' ? 'px-2 py-0.5 text-xs' : 'px-3 py-1 text-xs';

  return (
    <span
      className={`inline-flex items-center gap-1.5 rounded-full font-medium ${padding}`}
      style={{ backgroundColor: colors.bg, color: colors.text }}
    >
      <span
        className="w-1.5 h-1.5 rounded-full flex-shrink-0"
        style={{ backgroundColor: colors.dot }}
      />
      {label}
    </span>
  );
}
